# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: summary.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'summary.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsummary.proto\x12\x07summary\"B\n\x10SummarizeRequest\x12\x0f\n\x07note_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0f\n\x07user_id\x18\x03 \x01(\t\"5\n\x11SummarizeResponse\x12\x0f\n\x07note_id\x18\x01 \x01(\t\x12\x0f\n\x07summary\x18\x02 \x01(\t2T\n\x0eSummaryService\x12\x42\n\tSummarize\x12\x19.summary.SummarizeRequest\x1a\x1a.summary.SummarizeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'summary_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUMMARIZEREQUEST']._serialized_start=26
  _globals['_SUMMARIZEREQUEST']._serialized_end=92
  _globals['_SUMMARIZERESPONSE']._serialized_start=94
  _globals['_SUMMARIZERESPONSE']._serialized_end=147
  _globals['_SUMMARYSERVICE']._serialized_start=149
  _globals['_SUMMARYSERVICE']._serialized_end=233
# @@protoc_insertion_point(module_scope)
